<table align="center" width=100%>
    <tr>
        <td width="15%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Take-Home <br>(Day 4)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Import the required libraries**

In [1]:
# type your code here
# type your code here
import pandas as pd 

# import 'numpy' 
import numpy as np

# to suppress warnings 
from warnings import filterwarnings
filterwarnings('ignore')

# import statsmodels
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

# import 'stats' package from scipy library
from scipy import stats

# import the functions to perform Chi-square tests
from scipy.stats import chi2_contingency
from scipy.stats import chi2
from scipy.stats import chisquare

# function to perform post-hoc test
import statsmodels.stats.multicomp as mc

# to test the normality 
from scipy.stats import shapiro


### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. The sales manager at an electronics company wants to study if online sales of their products in 2019 follow the same distribution as the online sales of products in 2015. He collected the sample of 300 products sold in 2019. Help the manager to test his claim using p-value technique at a 99% confidence level.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<img src='chi_2.png'>

In [2]:
observed=np.array([85,90,125])
observed

array([ 85,  90, 125])

In [3]:
expected=np.array([0.38,0.20,0.42])*300
expected

array([114.,  60., 126.])

In [4]:
chi_critical=stats.chi2.isf(0.01,df=(len(expected)-1))
chi_critical

9.210340371976182

In [5]:
stat,pval=stats.chisquare(f_obs=observed,f_exp=expected)
stat,pval

(22.38512949039265, 1.3776246111575923e-05)

In [ ]:
#test stat is >9.21 and pval<0.01 so we reject the null hypothesis.

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Use hypothesis testing to check if the type of car is dependent on the type of car's transmission. Test the hypothesis with 95% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<img src='chi_ind.png'>

In [ ]:
#H0: type of car is dependent on the type of car's transmission
#H1: type of car is not dependent on the type of car's transmission

In [8]:
# type your code here
observed=np.array([[104,85,78],[35,61,72]])
observed

array([[104,  85,  78],
       [ 35,  61,  72]])

In [10]:
chi_critical=stats.chi2.isf(0.05,df=2)
chi_critical

5.991464547107983

In [13]:
stat,p_value,dof,exp_val=stats.chi2_contingency(observed=observed,correction=False)
print('test_stat :',stat)
print('p_value :',p_value)
print('expected_value :',exp_val)

test_stat : 16.774829953535356
p_value : 0.00022771516717561853
expected_value : [[85.31724138 89.6137931  92.06896552]
 [53.68275862 56.3862069  57.93103448]]


In [ ]:
#test_stat>5.99 and p_val<0.01 so we reject null hypothesis.
#type of car is not dependent on the type of car's transmission

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. A company produces leather belts on three different production lines. The number of defective belts produced by each line is recorded. Test if all the production lines produce on an average equal number of defective belts. Use the p-value technique to test at 5% level of significance.  </b>
                </font>
            </div>
        </td>
    </tr>
</table>

Use the data given in the excel file `defective_prod.xlsx`

In [11]:
# type your code here
df=pd.read_excel('defective_prod.xlsx')
df.head()

production_line  def_belts
0               A          5
1               C          2
2               B          3
3               A          4
4               C          1

In [12]:
df['production_line'].value_counts()

A    7
C    7
B    7
Name: production_line, dtype: int64

In [14]:
stat,pval = shapiro(df['def_belts'])
stat,pval

(0.9259648323059082, 0.11425024271011353)

In [15]:
A=df[df['production_line']=='A']['def_belts']
B=df[df['production_line']=='B']['def_belts']
C=df[df['production_line']=='C']['def_belts']


In [22]:
stat, p_value = stats.levene(A,B,C)
stat,p_value

(0.8375, 0.4489726403784061)

In [23]:
t = df['production_line'].nunique()
N = df['def_belts'].value_counts().sum()

In [24]:
f_critical = stats.f.isf(q=0.05,dfn=t-1,dfd=N-t)
print('f_critical ',round(f_critical,2))

f_critical  3.55


In [25]:
f_test,pval = stats.f_oneway(A,B,C)
print('f-statistic ',f_test)
print('pval',pval )

f-statistic  0.8384615384615386
pval 0.44857788134106824


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. The company wants to decide their advertisement strategies for their new smartwatch. The manager collects the advertising cost (in dollars) for four different mediums. Test if the company is spending on average an equal amount on all the advertising mediums using a critical value approach with 99% confidence.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

Use the data given in the excel file `ad_cost.xlsx`

In [14]:
df_ad=pd.read_excel('ad_cost.xlsx')

In [15]:
df_ad.head()

medium  cost
0  Snapmart   252
1   Picbook   378
2    Funsta   312
3   Klicker   297
4   Picbook   361

In [18]:
df_ad['medium'].value_counts()

Snapmart    3
Picbook     3
Klicker     3
Funsta      3
Name: medium, dtype: int64

In [ ]:
H0:the company is spending on average an equal amount on all the advertising mediums
H1:the company is not spending on average an equal amount on all the advertising mediums

In [24]:
a=df_ad[df_ad['medium']=='Snapmart']['cost']
b=df_ad[df_ad['medium']=='Picbook']['cost']
c=df_ad[df_ad['medium']=='Klicker']['cost']
d=df_ad[df_ad['medium']=='Funsta']['cost']

In [25]:
stat,p_val=stats.shapiro(df_ad['cost'])
print('p_value :',p_val)

p_value : 0.9111207723617554


In [26]:
#p_val>0.01 is normally distributed

In [28]:
stat,p_val=stats.levene(a,b,c,d)
print(p_val)

0.7230913376085835


In [29]:
#p_val>0.01 has equal varience

In [32]:
t=df_ad['medium'].nunique()
t

4

In [35]:
N=df_ad['cost'].value_counts().sum()
N

12

In [37]:
f_critical_val=stats.f.isf(0.01,dfn=3,dfd=8)
f_critical_val

7.590991947598852

In [39]:
f_stat,p_val=stats.f_oneway(a,b,c,d)
f_stat,p_val

(14.880471006443026, 0.001230153853232096)

In [ ]:
#f_stat>f_critical and p_val<0.01 we reject the null hypothesis