<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [26]:
#import numpy as np
import numpy as np

In [27]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]


list_temperature = np.array(list_temperature)
list_temperature

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [4]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
weight = np.array([74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82])
weight

array([74.2, 85. , 74. , 67.9, 52. , 70.5, 86. , 51.8, 64. , 82. ])

In [5]:
weight[weight>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
random_number = np.random.randint(20,40,10)

In [8]:
random_number

array([37, 32, 37, 27, 39, 26, 36, 23, 35, 21])

In [ ]:
#It is possible to generate same random number everytime by the function
np.random.seed()

In [25]:
np.random.seed(41)
random_number = np.random.randint(20,41,10)
random_number

array([20, 23, 32, 22, 36, 21, 39, 33, 32, 23])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [49]:
# create array with first five positive integers
array_integer = np.array([1,2,3,4,5])
array_integer

array([1, 2, 3, 4, 5])

In [52]:
np.power(array_integer,5)

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
odd_number_array= np.arange(51,100,2)
odd_number_array

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [22]:
#create new array
array_A= np.array([[2,4,6],[5,3,8],[8,9,2]])
print(array_A)

[[2 4 6]
 [5 3 8]
 [8 9 2]]


In [23]:
array_A.sum(axis=0)

array([15, 16, 16])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [54]:
num= np.array([42, 87, 90, 14, 32, 75, 61, 80, 92])
print("remainder of an array : " ,num%8)

remainder of an array :  [2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [18]:
#create a 1D array of own choice 
abc=np.arange(1,21)
abc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
abc=abc.reshape(4,5)
abc

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
abc[1]

array([ 6,  7,  8,  9, 10])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [16]:
prices_monday = np.array([10, 30, 50, 60, 90])

prices_tuesday = np.array([50, 20, 80, 125, 10, 70])

np.intersect1d(prices_monday,prices_tuesday)

array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [18]:
weights=np.array([57, 69, 54, 65 ,71, 62, 56])
heights=np.array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] )
print("weights are : " ,weights)
print("hights are : ",heights)
BMI=print("BMI of persons are :",weights/heights**2)

weights are :  [57 69 54 65 71 62 56]
hights are :  [1.59 1.75 1.66 1.74 1.64 1.72 1.53]
BMI of persons are : [22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [20]:
array1 = np.array([[[3, 4], [8, 2],[5, 9]]])
new_array=np.insert(array1,obj=3,values=[5,7],axis=1)
new_array


array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [21]:
matrix=np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [24]:
M = np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
M

array([[15, 17, 45, 56],
       [ 7, 42, 15, 63],
       [54,  3, 61, 41],
       [ 0, 87, 16, 20]])

In [25]:
np.transpose(M)

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [70]:
#create new array 
array_A1 = np.array([[5,10],[10,15]])
array_A2 =np.array([[2,4],[8,16]])

print(array_A1)
print(array_A2)

#combine both array vertically
np.vstack([array_A2,array_A1])

[[ 5 10]
 [10 15]]
[[ 2  4]
 [ 8 16]]


array([[ 2,  4],
       [ 8, 16],
       [ 5, 10],
       [10, 15]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [22]:
#creating 2 array
array_num_A1=np.array([[-15,5,45],[25,50,75]])
array_num_A2=np.array([[12,72],[65,56]])

print(array_num_A1)
print(array_num_A2)

#combine 2 array horizontally
np.hstack([array_num_A2,array_num_A1])


[[-15   5  45]
 [ 25  50  75]]
[[12 72]
 [65 56]]


array([[ 12,  72, -15,   5,  45],
       [ 65,  56,  25,  50,  75]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [15]:
A = np.array([[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]])
print(A)

np.vsplit(A,3)


[[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]]


[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [10]:
B = np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
print(B)

[[ 8  7  0  9]
 [ 2 -3  5 10]
 [ 8  5 -1  3]]


In [11]:
np.hsplit(B,2)

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

In [13]:
np.hsplit(B,4)

[array([[8],
        [2],
        [8]]),
 array([[ 7],
        [-3],
        [ 5]]),
 array([[ 0],
        [ 5],
        [-1]]),
 array([[ 9],
        [10],
        [ 3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [16]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]

for data in (zip(L1,L2)):
    print(data)

(45, 21)
(67, 52)
(56, 64)
(71, 10)
(54, 49)
(62, 74)
(56, 26)


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [30]:
numbers = np.array([6, 5, 3, 15])
print(numbers)

for x in np.nditer(numbers):
    print(((2*x-1)/x+5))

[ 6  5  3 15]
6.833333333333333
6.8
6.666666666666667
6.933333333333334


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [0]:
# type your code here